from _typeshed import Incomplete

def create_route(app, engineio_server, engineio_endpoint) -> None: ...
def translate_request(request): ...
def make_response(status, headers, payload, environ): ...

class WebSocket:
    handler: Incomplete
    def __init__(self, handler, server) -> None: ...
    environ: Incomplete
    async def __call__(self, environ): ...
    async def close(self) -> None: ...
    async def send(self, message) -> None: ...
    async def wait(self): ...
