from _typeshed import Incomplete
from eventlet.websocket import WebSocketWSGI as _WebSocketWSGI

class EventletThread:
    target: Incomplete
    args: Incomplete
    kwargs: Incomplete
    g: Incomplete
    def __init__(self, target, args: Incomplete | None = None, kwargs: Incomplete | None = None) -> None: ...
    def start(self) -> None: ...
    def join(self): ...

class WebSocketWSGI(_WebSocketWSGI):
    def __init__(self, handler, server) -> None: ...
    def __call__(self, environ, start_response): ...
