from .. import exceptions as exceptions
from _typeshed import Incomplete

def get_tornado_handler(engineio_server): ...
def translate_request(handler): ...
def make_response(status, headers, payload, environ) -> None: ...

class WebSocket:
    handler: Incomplete
    tornado_handler: Incomplete
    def __init__(self, handler, server) -> None: ...
    environ: Incomplete
    async def __call__(self, environ) -> None: ...
    async def close(self) -> None: ...
    async def send(self, message) -> None: ...
    async def wait(self): ...
