from . import base_socket as base_socket, exceptions as exceptions, packet as packet, payload as payload

class AsyncSocket(base_socket.BaseSocket):
    async def poll(self): ...
    async def receive(self, pkt) -> None: ...
    async def check_ping_timeout(self): ...
    async def send(self, pkt) -> None: ...
    async def handle_get_request(self, environ): ...
    async def handle_post_request(self, environ) -> None: ...
    closing: bool
    closed: bool
    async def close(self, wait: bool = True, abort: bool = False) -> None: ...
    def schedule_ping(self) -> None: ...
