from . import base_socket as base_socket, exceptions as exceptions, packet as packet, payload as payload

class Socket(base_socket.BaseSocket):
    def poll(self): ...
    def receive(self, pkt) -> None: ...
    def check_ping_timeout(self): ...
    def send(self, pkt) -> None: ...
    def handle_get_request(self, environ, start_response): ...
    def handle_post_request(self, environ) -> None: ...
    closing: bool
    closed: bool
    def close(self, wait: bool = True, abort: bool = False) -> None: ...
    def schedule_ping(self) -> None: ...
